CREATE DATABASE portaldb;

CREATE USER 'bob'@'localhost' IDENTIFIED BY 'Qwerty1-';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON portaldb.* TO 'bob'@'localhost';